services:
  - type: web
    name: xlook-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGIN
        value: https://xlook-8yl048kgu-ranitisking-gmailcoms-projects.vercel.app
      - key: MONGO_URI
        value: mongodb://localhost:27017/url-safety-checker
      - key: VIRUSTOTAL_API_KEY
        value: 259f6c5ba111f2de0b64fd88796afed491b25e86f0954ceccd732ace927aa8ea
      - key: GOOGLE_SAFE_BROWSING_API_KEY
        value: AIzaSyBlOp2IbU7wbH5P4Klaa2H3gi3qQzQuRf8
      - key: IPINFO_API_KEY
        value: 340008b211ac42
