services:
  - type: web
    name: xlook-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGIN
        generateValue: true
      - key: MONGO_URI
        generateValue: true
      - key: VIRUSTOTAL_API_KEY
        generateValue: true
      - key: GOOGLE_SAFE_BROWSING_API_KEY
        generateValue: true
      - key: IPINFO_API_KEY
        generateValue: true
